spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ENC(EX5wEmMpseubDTq8Q59HSZtw5hQYmWRtOMuPtogI6lk=)
            client-secret: ENC(AS/IB1aBdzeOhjBLe2npwzFlavOZ6xX8)
            redirect-uri: http://localhost:8088/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: ENC(gdt5xlq0of0/zDHpSvFV7urHy6HMvoDyqUYPZA2WwCzqM1eXJTinvGPYa2fsuygP)
            client-secret: ENC(YidZs8LQrWUFH780rLaMeOsu08/A6Aw9JNDj5WTFEKNAGJxGa0LyLNcqiDoQ6tYK)
            redirect-uri: http://localhost:8088/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id